### ISSUE TITLE
forum issue

### ISSUE THREAD

**Issue by hfjxjjd123** [SOPT-all/35-SOPTKATHON-SERVER-web3#1]
# [요구사항 분석]
features list-up  
투두리스트
- 투두 리스트를 추가한다
- 투두 리스트 불러온다
- 투두 리스트를 삭제한다
- 투두 리스트 변경한다
- 누적된 투두 리스트 기록을 가져온다

# [공수산정]
이학림  
- [x] 문서관리
- [x] 전체 일별 불로오기 api 구현
- [x] 성공률 조회 api 구현

신민규
- [x] 투두리스트 등록
- [x] 투두리스트 수정
- [x] 투두리스트 완료 기능
- [x] 투두리스트 불러오기

# [설계도 작성]
## ERD
<img width="923" alt="image" src="https://github.com/user-attachments/assets/7200b5a0-1620-44c6-a17c-066d852399d4">  
  
## API 명세서  
[API명세서](https://www.notion.so/API-1449eb1c52e981d6bca0dd60c1b101bc)

**Comment by daehwan2da** [comment]
민규 학림 두분이서 끝까지 포기하지 않고 구현을 완성하는 모습이 인상깊었어요
마지막에 CORS 로 어려움이 있었지만, 왜 마무리에 그런 이슈가 있었을지 한번 고민해보면 좋을것같아요
(관리 포인트가 두가지고 파편화되어있는것을 최소화시키는 설계를 고민해보면 좋을듯하네요)
(추가로 CORS 에 대해서도 깊은 학습을 하면, 왜 저런 문제가 발생했었는지 더 이해할 수 있을것같아요)

아주 잘 하셨습니다~ 고생하셨습니다 짱
